sh tests/exhaustive/acceptOutput.sh tests/exhaustive/basic/restricted03                   
sh tests/exhaustive/acceptOutput.sh tests/exhaustive/basic/partition_01                   
sh tests/exhaustive/acceptOutput.sh tests/exhaustive/basic/relation05_set_fixed_direct    
sh tests/exhaustive/acceptOutput.sh tests/exhaustive/basic/mset01_find                    
sh tests/exhaustive/acceptOutput.sh tests/exhaustive/basic/enum05                         
sh tests/exhaustive/acceptOutput.sh tests/exhaustive/basic/function_partial_int_06        
sh tests/exhaustive/acceptOutput.sh tests/exhaustive/basic/set01_1                        
sh tests/exhaustive/acceptOutput.sh tests/exhaustive/basic/mset04                         
sh tests/exhaustive/acceptOutput.sh tests/exhaustive/basic/mset02                         
sh tests/exhaustive/acceptOutput.sh tests/exhaustive/basic/function_total_int_set_01      
sh tests/exhaustive/acceptOutput.sh tests/exhaustive/basic/mset05                         
sh tests/exhaustive/acceptOutput.sh tests/exhaustive/basic/relation06_set_bounded_direct  
sh tests/exhaustive/acceptOutput.sh tests/exhaustive/basic/mset06_2                       
sh tests/exhaustive/acceptOutput.sh tests/exhaustive/basic/comprehension_02_2             
sh tests/exhaustive/acceptOutput.sh tests/exhaustive/basic/cut_01_off                     
sh tests/exhaustive/acceptOutput.sh tests/exhaustive/basic/variant01                      
sh tests/exhaustive/acceptOutput.sh tests/exhaustive/basic/sequence_injective_01          
sh tests/exhaustive/acceptOutput.sh tests/exhaustive/basic/relation05_set_fixed_setty     
sh tests/exhaustive/acceptOutput.sh tests/exhaustive/basic/mset03_1                       
sh tests/exhaustive/acceptOutput.sh tests/exhaustive/basic/comprehension_01_2             
sh tests/exhaustive/acceptOutput.sh tests/exhaustive/basic/partition_03                   
sh tests/exhaustive/acceptOutput.sh tests/exhaustive/basic/toSet_comprehension            
sh tests/exhaustive/acceptOutput.sh tests/exhaustive/basic/relation06_set_bounded_setty   
sh tests/exhaustive/acceptOutput.sh tests/exhaustive/basic/partition_02                   
sh tests/exhaustive/acceptOutput.sh tests/exhaustive/basic/enum06                         
sh tests/exhaustive/acceptOutput.sh tests/exhaustive/basic/function_partial_int_05        
sh tests/exhaustive/acceptOutput.sh tests/exhaustive/basic/set01_2                        
sh tests/exhaustive/acceptOutput.sh tests/exhaustive/basic/mset07                         
sh tests/exhaustive/acceptOutput.sh tests/exhaustive/basic/setOfSet03                     
sh tests/exhaustive/acceptOutput.sh tests/exhaustive/basic/function_partial_int_03        
sh tests/exhaustive/acceptOutput.sh tests/exhaustive/basic/function_partial_int_04        
sh tests/exhaustive/acceptOutput.sh tests/exhaustive/basic/mset06_1                       
sh tests/exhaustive/acceptOutput.sh tests/exhaustive/basic/set01_3                        
sh tests/exhaustive/acceptOutput.sh tests/exhaustive/basic/function_partial_int_param     
sh tests/exhaustive/acceptOutput.sh tests/exhaustive/basic/sequence_injective_02          
sh tests/exhaustive/acceptOutput.sh tests/exhaustive/basic/enum05-unnamed                 
sh tests/exhaustive/acceptOutput.sh tests/exhaustive/basic/set02                          
sh tests/exhaustive/acceptOutput.sh tests/exhaustive/basic/mset03_2                       
sh tests/exhaustive/acceptOutput.sh tests/exhaustive/basic/set_card_02                    
sh tests/exhaustive/acceptOutput.sh tests/exhaustive/basic/comprehension_03_2             
sh tests/exhaustive/acceptOutput.sh tests/exhaustive/issues/261                           
sh tests/exhaustive/acceptOutput.sh tests/exhaustive/issues/284                           
sh tests/exhaustive/acceptOutput.sh tests/exhaustive/issues/200                           
