#!/bin/bash

# run this script on a terminal.
# then, from another terminal run `conjure {problemname}.essence`
# conjure will submit task to this script

qFile=`conjureBF pathOfQueueFile`

on_die()
{
    echo "Stopping server..."
    rm $qFile
    exit 0
}

trap 'on_die' SIGHUP SIGINT SIGTERM

if [ -f $qFile ];
then
    echo "Only one instance of conjure-server can run at a time"
    echo "    $qFile must be a left-over from previous runs,"
    echo "    remove that file and try again"
else
    echo "You can now run conjure on a different terminal"
    echo "    Usage: conjure {problem-name}.essence"
    touch $qFile
    (
        for i in `seq 1 256`
        do
            echo " true " >> $qFile
        done
    )
    tail -f $qFile | parallel -u
fi

