#!/bin/bash

# get savilerow installation directory
DIR="$( cd "$( dirname "$0" )" && pwd )"

case "$@" in
    *"-cgroups"*)
        if [ $(uname) = "Darwin" ]; then
            echo "Ignoring -cgroups on macOS"
            java -ea -XX:ParallelGCThreads=1 -Djava.library.path=$DIR/lib/ -Xmx8G -jar "$DIR/savilerow.jar" "$@"
        else
            TIMESTAMP=$(date +%s)
            GROUP_NAME="savilerow_${TIMESTAMP}_$$"

            echo "Using cgroups, group name: $GROUP_NAME"

            cgcreate -g cpu:/$GROUP_NAME
            cgset -r cpu.cfs_quota_us=1000000 $GROUP_NAME
            cgset -r cpu.cfs_period_us=1000000 $GROUP_NAME
            cgexec -g cpu:$GROUP_NAME java -ea -XX:ParallelGCThreads=1 -Djava.library.path=$DIR/lib/ -Xmx8G -jar "$DIR/savilerow.jar" "$@"
            cgdelete -g cpu:/$GROUP_NAME
        fi
    ;;
    *)
        java -ea -XX:ParallelGCThreads=1 -Djava.security.egd=file:/dev/urandom -Djava.library.path=$DIR/lib/ -Xmx8G -Xms8G -Xss1G -jar "$DIR/savilerow.jar" "$@"
    ;;
esac
