<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>essence</string>
		<string>eprime</string>
		<string>param</string>
		<string>rule</string>
		<string>repr</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>name</key>
	<string>Essence</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(forall|allDifferent|dim|toSet|toMSet|toRelation|maximising|minimising|forAll|exists|toInt|sum|be|bijective|bool|by|complete|defined|domain|in|false|find|from|function|given|image|indexed|injective|int|intersect|freq|lambda|language|letting|matrix|maxNumParts|maxOccur|maxPartSize|maxSize|minNumParts|minOccur|minPartSize|minSize|mset|numParts|of|partial|partition|partSize|preImage|quantifier|range|regular|relation|representation|set|size|subset|subsetEq|such|supset|supsetEq|surjective|that|together|enum|total|true|new|type|tuple|union|where|branching|on)\b</string>
			<key>name</key>
			<string>keyword.control.essence</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(&lt;=lex|&gt;=lex|&lt;lex|&gt;lex|=|!=|&lt;=|&gt;=|&lt;|&gt;)</string>
			<key>name</key>
			<string>constant.language.comparison.essence</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(!|-&gt;|&lt;-&gt;|/\\|\\/|\|)</string>
			<key>name</key>
			<string>constant.language.logical.essence</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\-|\+|\*|%|\^|\/)</string>
			<key>name</key>
			<string>constant.language.arithmetic.essence</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.essence</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.essence</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\$</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.essence</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>comment.line.character.essence</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&lt;!\\)\\$\n</string>
					<key>name</key>
					<string>punctuation.separator.continuation.essence</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.essence</string>
	<key>uuid</key>
	<string>7D5C5AD5-1705-4155-8791-4096F70B5510</string>
</dict>
</plist>
