#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Bilal Syed Hussain
# Created Mon 31 Dec 2012 2:53:35 +0000
import sys
from os.path import basename
from itertools import izip_longest

"""
Outputs a param file e.g
language Essence 1.3
letting <name1> be <value1>
letting <name2> be <value2>
"""

def grouper(n, iterable):
    args = [iter(iterable)] * n
    return izip_longest(*args)


Header = "language Essence 1.3"
lines = [Header]
args = sys.argv[1:]

if not args or len(args) % 2 != 0:
    sys.exit('%s: [name val]* ' % basename(sys.argv[0]))

for name, val in grouper(2, args):
    lines.append("letting {} be {}".format(name,val))

print "\n".join(lines)

